version: '3.8'

services:
  wordpress:
    # getting latest WordPress version available on Docker  
    image: wordpress:latest
    ports:
      - "8000:80"
    env_file:
      - .env
    volumes:
      # mapping wordpress_data as defined below to var/www/html
      - wordpress_data:/var/www/html
      # mapping our local custom theme directory to /var/www/html/wp-content/themes/big-city-3
      - ./themes/biggest-city:/var/www/html/wp-content/themes/big-city-3
      # mapping our local custom plugin directory to /var/www/html/wp-content/plugins/custom-plugin
      - ./plugins/custom-plugin:/var/www/html/wp-content/plugins/custom-plugin
      # mapping our local php.ini file to /usr/local/etc/php/php.ini
      - ./php.ini:/usr/local/etc/php/php.ini

  db:
    # getting the latest Docker image for MariaDB
    image: mariadb:latest
    env_file:
      - .env
    volumes:
      # mapping db_data as defined below to /var/lib/mysql
      - db_data:/var/lib/mysql

# defining volumes so that data persists when Docker containers restart, stop, or are removed
volumes:
  wordpress_data:
  db_data:


